In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("world-happiness-report - world-happiness-report.csv")

In [5]:
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268

In [6]:
df.tail()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
1944,Zimbabwe,2016,3.735,7.984,0.768,54.4,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.0,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.6,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.2,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.8,0.643,-0.009,0.789,0.703,0.346

In [8]:
df.shape

(1949, 11)

In [11]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [12]:
df

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [13]:
df.columns

Index(['Country name', 'year', 'Life Ladder', 'Log GDP per capita',
       'Social support', 'Healthy life expectancy at birth',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption', 'Positive affect', 'Negative affect'],
      dtype='object')

In [14]:
df.sample(8)

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
272,Cambodia,2015,4.162,8.173,0.729,60.40,0.956,0.210,0.825,0.813,0.399
492,Ecuador,2015,5.964,9.384,0.856,67.60,0.801,-0.114,0.666,0.851,0.323
461,Denmark,2018,7.649,10.935,0.958,72.40,0.935,0.018,0.151,0.821,0.206
94,Azerbaijan,2007,4.568,9.386,0.753,62.26,0.522,-0.207,0.871,0.521,0.284
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
691,Honduras,2012,4.602,8.530,0.779,65.94,0.700,-0.003,0.871,0.847,0.294
562,Finland,2019,7.780,10.792,0.937,72.00,0.948,-0.052,0.195,0.755,0.181
971,Lebanon,2009,5.206,9.830,0.736,65.08,0.665,0.071,0.937,0.528,0.401

In [15]:
df.info

<bound method DataFrame.info of      Country name  year  Life Ladder  Log GDP per capita  Social support  \
0     Afghanistan  2008        3.724               7.370           0.451
1     Afghanistan  2009        4.402               7.540           0.552
2     Afghanistan  2010        4.758               7.647           0.539
3     Afghanistan  2011        3.832               7.620           0.521
4     Afghanistan  2012        3.783               7.705           0.521
...           ...   ...          ...                 ...             ...
1944     Zimbabwe  2016        3.735               7.984           0.768
1945     Zimbabwe  2017        3.638               8.016           0.754
1946     Zimbabwe  2018        3.616               8.049           0.775
1947     Zimbabwe  2019        2.694               7.950           0.759
1948     Zimbabwe  2020        3.160               7.829           0.717

      Healthy life expectancy at birth  Freedom to make life choices  \
0                                50.80                         0.718
1                                51.20                         0.679
2                                51.60                         0.600
3                                51.92                         0.496
4                                52.24                         0.531
...                                ...                           ...
1944                             54.40                         0.733
1945                             55.00                         0.753
1946                             55.60                         0.763
1947                             56.20                         0.632
1948                             56.80                         0.643

      Generosity  Perceptions of corruption  Positive affect  Negative affect
0          0.168                      0.882            0.518            0.258
1          0.190                      0.850            0.584            0.237
2          0.121                      0.707            0.618            0.275
3          0.162                      0.731            0.611            0.267
4          0.236                      0.776            0.710            0.268
...          ...                        ...              ...              ...
1944      -0.095                      0.724            0.738            0.209
1945      -0.098                      0.751            0.806            0.224
1946      -0.068                      0.844            0.710            0.212
1947      -0.064                      0.831            0.716            0.235
1948      -0.009                      0.789            0.703            0.346

[1949 rows x 11 columns]>

In [16]:
df.dtypes

Country name                         object
year                                  int64
Life Ladder                         float64
Log GDP per capita                  float64
Social support                      float64
Healthy life expectancy at birth    float64
Freedom to make life choices        float64
Generosity                          float64
Perceptions of corruption           float64
Positive affect                     float64
Negative affect                     float64
dtype: object

In [17]:
df.describe()

,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
count,1949.000000,1949.000000,1913.000000,1936.000000,1894.000000,1917.000000,1860.000000,1839.000000,1927.000000,1933.000000
mean,2013.216008,5.466705,9.368453,0.812552,63.359374,0.742558,0.000103,0.747125,0.710003,0.268544
std,4.166828,1.115711,1.154084,0.118482,7.510245,0.142093,0.162215,0.186789,0.107100,0.085168
min,2005.000000,2.375000,6.635000,0.290000,32.300000,0.258000,-0.335000,0.035000,0.322000,0.083000
25%,2010.000000,4.640000,8.464000,0.749750,58.685000,0.647000,-0.113000,0.690000,0.625500,0.206000
50%,2013.000000,5.386000,9.460000,0.835500,65.200000,0.763000,-0.025500,0.802000,0.722000,0.258000
75%,2017.000000,6.283000,10.353000,0.905000,68.590000,0.856000,0.091000,0.872000,0.799000,0.320000
max,2020.000000,8.019000,11.648000,0.987000,77.100000,0.985000,0.698000,0.983000,0.944000,0.705000

In [18]:
df.isnull()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1944,False,False,False,False,False,False,False,False,False,False,False
1945,False,False,False,False,False,False,False,False,False,False,False
1946,False,False,False,False,False,False,False,False,False,False,False
1947,False,False,False,False,False,False,False,False,False,False,False
1948,False,False,False,False,False,False,False,False,False,False,False

In [32]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [34]:
df.columns=df.columns.str.strip().str.lower().str.replace(" ","_")
df.columns

Index(['country_name', 'year', 'life_ladder', 'log_gdp_per_capita',
       'social_support', 'healthy_life_expectancy_at_birth',
       'freedom_to_make_life_choices', 'generosity',
       'perceptions_of_corruption', 'positive_affect', 'negative_affect'],
      dtype='object')

In [21]:
df.isnull().sum()

Country name                          0
year                                  0
Life Ladder                           0
Log GDP per capita                   36
Social support                       13
Healthy life expectancy at birth     55
Freedom to make life choices         32
Generosity                           89
Perceptions of corruption           110
Positive affect                      22
Negative affect                      16
dtype: int64

In [35]:
important_cols = [
    'life_ladder',
    'log_gdp_per_capita',
    'social_support',
    'healthy_life_expectancy_at_birth',
    'freedom_to_make_life_choices'
]

for col in important_cols:
    df[col] = df[col].fillna(df[col].mean())

In [37]:
df['generosity'] = df['generosity'].fillna(df['generosity'].mean())
df['perceptions_of_corruption'] = df['perceptions_of_corruption'].fillna(df['perceptions_of_corruption'].mean())

In [38]:
df=df.dropna()

In [39]:
df.isnull().sum()

country_name                        0
year                                0
life_ladder                         0
log_gdp_per_capita                  0
social_support                      0
healthy_life_expectancy_at_birth    0
freedom_to_make_life_choices        0
generosity                          0
perceptions_of_corruption           0
positive_affect                     0
negative_affect                     0
dtype: int64

In [40]:
df.shape

(1925, 11)

In [41]:
df = df.drop_duplicates()

In [42]:
df

,country_name,year,life_ladder,log_gdp_per_capita,social_support,healthy_life_expectancy_at_birth,freedom_to_make_life_choices,generosity,perceptions_of_corruption,positive_affect,negative_affect
0,Afghanistan,2008,3.724,7.370,0.451,50.80,0.718,0.168,0.882,0.518,0.258
1,Afghanistan,2009,4.402,7.540,0.552,51.20,0.679,0.190,0.850,0.584,0.237
2,Afghanistan,2010,4.758,7.647,0.539,51.60,0.600,0.121,0.707,0.618,0.275
3,Afghanistan,2011,3.832,7.620,0.521,51.92,0.496,0.162,0.731,0.611,0.267
4,Afghanistan,2012,3.783,7.705,0.521,52.24,0.531,0.236,0.776,0.710,0.268
...,...,...,...,...,...,...,...,...,...,...,...
1944,Zimbabwe,2016,3.735,7.984,0.768,54.40,0.733,-0.095,0.724,0.738,0.209
1945,Zimbabwe,2017,3.638,8.016,0.754,55.00,0.753,-0.098,0.751,0.806,0.224
1946,Zimbabwe,2018,3.616,8.049,0.775,55.60,0.763,-0.068,0.844,0.710,0.212
1947,Zimbabwe,2019,2.694,7.950,0.759,56.20,0.632,-0.064,0.831,0.716,0.235
1948,Zimbabwe,2020,3.160,7.829,0.717,56.80,0.643,-0.009,0.789,0.703,0.346

In [43]:
df.groupby('country_name')['life_ladder'].mean()

country_name
Afghanistan    3.594667
Albania        5.019385
Algeria        5.379286
Angola         4.420250
Argentina      6.310133
                 ...
Venezuela      6.019867
Vietnam        5.315923
Yemen          3.912250
Zambia         4.551714
Zimbabwe       3.882600
Name: life_ladder, Length: 164, dtype: float64

In [45]:
df.groupby('country_name').size()

country_name
Afghanistan    12
Albania        13
Algeria         7
Angola          4
Argentina      15
               ..
Venezuela      15
Vietnam        13
Yemen          12
Zambia         14
Zimbabwe       15
Length: 164, dtype: int64

In [46]:
df.groupby('country_name')['life_ladder'].agg(['mean', 'min', 'max'])

                  mean    min    max
country_name
Afghanistan   3.594667  2.375  4.758
Albania       5.019385  4.511  5.867
Algeria       5.379286  4.745  6.355
Angola        4.420250  3.795  5.589
Argentina     6.310133  5.793  6.776
...                ...    ...    ...
Venezuela     6.019867  4.041  7.478
Vietnam       5.315923  5.023  5.767
Yemen         3.912250  2.983  4.809
Zambia        4.551714  3.307  5.260
Zimbabwe      3.882600  2.694  4.955

[164 rows x 3 columns]

In [49]:
df.groupby(['country_name', 'year'])['life_ladder'].mean().reset_index()

     country_name  year  life_ladder
0     Afghanistan  2008        3.724
1     Afghanistan  2009        4.402
2     Afghanistan  2010        4.758
3     Afghanistan  2011        3.832
4     Afghanistan  2012        3.783
...           ...   ...          ...
1920     Zimbabwe  2016        3.735
1921     Zimbabwe  2017        3.638
1922     Zimbabwe  2018        3.616
1923     Zimbabwe  2019        2.694
1924     Zimbabwe  2020        3.160

[1925 rows x 3 columns]

In [50]:
df.groupby('country_name')['life_ladder'].mean().reset_index()

    country_name  life_ladder
0    Afghanistan     3.594667
1        Albania     5.019385
2        Algeria     5.379286
3         Angola     4.420250
4      Argentina     6.310133
..           ...          ...
159    Venezuela     6.019867
160      Vietnam     5.315923
161        Yemen     3.912250
162       Zambia     4.551714
163     Zimbabwe     3.882600

[164 rows x 2 columns]

In [51]:
df.groupby('year')['life_ladder'].mean().reset_index()

    year  life_ladder
0   2005     6.564200
1   2006     5.202886
2   2007     5.430772
3   2008     5.417139
4   2009     5.461496
5   2010     5.499175
6   2011     5.414228
7   2012     5.443754
8   2013     5.390437
9   2014     5.375085
10  2015     5.397197
11  2016     5.399479
12  2017     5.462363
13  2018     5.507743
14  2019     5.578685
15  2020     5.859181

In [53]:

df.groupby('country_name')[['log_gdp_per_capita','life_ladder']].mean()

              log_gdp_per_capita  life_ladder
country_name
Afghanistan             7.650833     3.594667
Albania                 9.384385     5.019385
Algeria                 9.334857     5.379286
Angola                  8.990000     4.420250
Argentina              10.033800     6.310133
...                          ...          ...
Venezuela               9.457757     6.019867
Vietnam                 8.638308     5.315923
Yemen                   8.313659     3.912250
Zambia                  8.066857     4.551714
Zimbabwe                7.850333     3.882600

[164 rows x 2 columns]